LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifndef SPIDERMONKEY_SDK_PATH
    SPIDERMONKEY_SDK_PATH := $(LOCAL_PATH)/../../..
endif

ifndef SPIDERMONKEY_DIST_PATH
	SPIDERMONKEY_DIST_PATH := $(SPIDERMONKEY_SDK_PATH)/js/src/build-android/dist
endif

LOCAL_EXPORT_C_INCLUDES := $(SPIDERMONKEY_DIST_PATH)/include
LOCAL_EXPORT_C_INCLUDES += $(SPIDERMONKEY_SDK_PATH)/js/src

LOCAL_SRC_FILES := $(SPIDERMONKEY_DIST_PATH)/lib/libjs_static.a

LOCAL_CPPFLAGS := -D__STDC_LIMIT_MACROS=1 -Wno-invalid-offsetof
LOCAL_EXPORT_CPPFLAGS := -D__STDC_LIMIT_MACROS=1 -Wno-invalid-offsetof

LOCAL_MODULE_FILENAME := js_static
LOCAL_MODULE := spidermonkey
include $(PREBUILT_STATIC_LIBRARY)
